/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/VueComponents/Button.vue')['default']
    Counter: typeof import('./src/components/VueComponents/Counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
  }
}
